setwd("E:/Poltek Gian/3/Data Mining/tb")
getwd()
install.packages("C50")
install.packages("printr")
library(C50)
library(printr)
dataset <- read.csv("Invistico_Airline_Final.csv", sep = ";")
dataset$satisfaction<-as.factor(dataset$satisfaction)
model <- C5.0(satisfaction ~., data=dataset)
summary(model)
plot(model)
datatesting <- dataset[,1:5]
predictions <- predict(model, dataset)
table(predictions, dataset$satisfaction)
